### ISSUE TITLE
Still get "invalid byte sequence in UTF-8" errors with Internet Explorer 

### ISSUE THREAD

**Issue by ncri** [singlebrook/utf8-cleaner#17]
Tested IE 11 on Win 7

**Comment by valscion** [comment]
Hi, I'm having the same issue.

I tested with a request where `env["QUERY_STRING"]` before sanitation was `H\xE4meenlinna` — clearly "Hämeenlinna" encoded in Windows-1252 and not UTF-8. I then checked what I'd get as a result of running

```ruby
sanitize_env(env)["QUERY_STRING"]
```

in debugger while I stopped at the middleware `#call` method — and I still got `H\xE4meenlinna` out, which was clearly incorrect and caused, and it caused the request to crash and burn, raising "invalid byte sequence in UTF-8" error.

I'm happy to create a test case for this scenario, if you so wish.

**Comment by sbleon** [comment]
Please do go ahead and create a test.

Since `\xE4` is not valid URI encoding (aka % encoding), the behavior I'd
suggest in this situation would be one of:
1. Remove the `\`, leaving `xE4`
2. Remove the entire 4 bytes of the character
3. Double the `\` so that it is escaped and doesn't get decoded.

I don't want UTF8-cleaner to have the responsibility of translating other
character sets (e.g. CP1252) to UTF-8, and I don't want it to facilitate
the use of improper encodings in URLs. I'm leaning towards option 3.

_______________________________________________
Leon Miller-Out - Singlebrook Technology - 607-330-0191

**Comment by valscion** [comment]
I'll see what I can do :)

I'm not sure double escaping the `\x4` would result in good user experience. In our case, the value would also be prefilled in a search input.

Do you think it'd make sense to use the [U+FFFD REPLACAMENT CHARACTER](http://www.fileformat.info/info/unicode/char/0fffd/index.htm) � in these cases instead? That way it might be more clear to the user that their special characters had some issues.

> used to replace an incoming character whose value is unknown or unrepresentable in Unicode

**Comment by sbleon** [comment]
I'd rather change the input as little as possible, so I'm still for
double-encoding. If there's a poor user experience, it's due to either

1. an archaic browser that doesn't do UTF-8
2. the developer not specifying UTF-8 encoding correctly in their
head/headers

In neither of this cases should we trying to be helpful, in my opinion, but
I do want to try to keep the request from crashing.

_______________________________________________
Leon Miller-Out - Singlebrook Technology - 607-330-0191

**Comment by valscion** [comment]
Yeah, you're right. Maybe the least surprising thing would be to remove the characters altogether? It feels like it would be what I'd expect this gem to do based on the README (emphasis mine):
> **Removes** invalid UTF-8 characters from the environment

**Comment by sbleon** [comment]
Good point! Can we actually remove the characters safely? If they're in an
invalid \xnn format, we might not know how many bytes they are supposed to
be, so it might be hard to remove them correctly.

_______________________________________________
Leon Miller-Out - Singlebrook Technology - 607-330-0191

**Comment by valscion** [comment]
A-ha! I'll make sure to add good test coverage to test these cases. If it turns out to be too difficult we'll at least have some code to talk about.

I'll try to get my hands dirty with this next week, feel free to ping me if there doesn't seem to be any progress.

**Comment by sbleon** [comment]
@ncri @valscion I think this may be addressed by the new version v0.1.1. It replaces Windows-encoded characters with their UTF8 equivalents. https://github.com/singlebrook/utf8-cleaner/blob/master/CHANGELOG.md

**Comment by valscion** [comment]
Wow, super! Thanks a bunch @sbleon :+1: I'll make sure to test this
